name: Build CI - Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: Windows

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: make -C 3_Implenentation/version1
    - name: 
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
